name: CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x
    
    - name: Install dependencies
      run: yarn
  
    - name: Run build
      run: yarn build
    
    - name: Upload dist to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: ".,!node_modules"
        target: "~/app/sisoc"
    
    - name: Run install scripts on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd ~/app/sisoc
          yarn
          ./node_modules/.bin/typeorm migration:run
          pm2 restart sisoc
